@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jan 24 14:42:04 -0600 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_main_unidad_control_behav -key {Behavioral:sim_1:Functional:tb_main_unidad_control} -tclbatch tb_main_unidad_control.tcl -view C:/Users/sel19/Documents/desktop/arquitecturaComputadoras/vivado/unidad_control_process_reloj_correcto/exito.wcfg -log simulate.log"
call xsim  tb_main_unidad_control_behav -key {Behavioral:sim_1:Functional:tb_main_unidad_control} -tclbatch tb_main_unidad_control.tcl -view C:/Users/sel19/Documents/desktop/arquitecturaComputadoras/vivado/unidad_control_process_reloj_correcto/exito.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
