# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design bloque_condicion has unconnected port flags_alu[3]}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[19] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[15] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[11] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[10] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[9] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[7] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[6] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design procesador has port instruccion[5] driven by constant 0}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.cache/wt} [current_project]
set_property parent.project_path {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/alu_bit.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/paquete_alu.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/bandera_alu.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/bloque_condicion.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/bloque_nivel.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/carta_uc.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/decodificador_instruccion.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/package_components.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/memoria_funcion.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/memoria_operacion.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/paquete_uc.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/main.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/memoriaPrograma.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/alu_bits.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/pila.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/archivoRegistros.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/memoriaDatos.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/uc.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/extensor_signo.vhd}
  {C:/Users/sel19/Documents/desktop/cosas que debo subir a git con orden/arqui/vivado/procesador_risc/escomips/escomips.srcs/sources_1/new/extensor_direccion.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top procesador -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef procesador.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file procesador_utilization_synth.rpt -pb procesador_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
