webtalk_init -webtalk_dir C:/Users/sel19/Documents/desktop/arquitecturaComputadoras/vivado/unidad_control_process_reloj_correcto/unidad_control_components.sim/sim_1/behav/xsim/xsim.dir/tb_main_unidad_control_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 24 14:44:20 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "419ede40-97de-444c-b163-82cc81e0e23e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "259eec769ac745fab4534df63e1b8c6e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "167" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "8" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1877740247 -regid "" -xml C:/Users/sel19/Documents/desktop/arquitecturaComputadoras/vivado/unidad_control_process_reloj_correcto/unidad_control_components.sim/sim_1/behav/xsim/xsim.dir/tb_main_unidad_control_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/sel19/Documents/desktop/arquitecturaComputadoras/vivado/unidad_control_process_reloj_correcto/unidad_control_components.sim/sim_1/behav/xsim/xsim.dir/tb_main_unidad_control_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/sel19/Documents/desktop/arquitecturaComputadoras/vivado/unidad_control_process_reloj_correcto/unidad_control_components.sim/sim_1/behav/xsim/xsim.dir/tb_main_unidad_control_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
